// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBallStores.Models;

#nullable disable

namespace TheBallStores.Migrations
{
    [DbContext(typeof(TheballStoreContext))]
    partial class TheballStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("TheBallStores.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaCT");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaChiTiet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaCt")
                        .HasName("PK__ChiTietD__27258E7446AD14B2");

                    b.HasIndex("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("TheBallStores.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaKh")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaVoucher")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'Mới đặt'");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHangs__129584AD370F3EB8");

                    b.HasIndex("MaKh");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("TheBallStores.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaSp")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaSp");

                    b.ToTable("HinhAnhSanPham", (string)null);
                });

            modelBuilder.Entity("TheBallStores.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaKH");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'Customer'");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E7C01B1ED");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("TheBallStores.Models.KichThuoc", b =>
                {
                    b.Property<int>("MaSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("MaSize")
                        .HasName("PK__KichThuo__A787E7ED598484B8");

                    b.ToTable("KichThuocs");
                });

            modelBuilder.Entity("TheBallStores.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhomLoai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSanPhams", (string)null);
                });

            modelBuilder.Entity("TheBallStores.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaSP");

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp");

                    b.HasIndex("MaLoai");

                    b.ToTable("SanPhams", (string)null);
                });

            modelBuilder.Entity("TheBallStores.Models.SanPhamChiTiet", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaSp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaSP");

                    b.Property<int?>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__SanPhamC__CDF0A11446FCB7A6");

                    b.HasIndex("MaSize");

                    b.HasIndex("MaSp");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("TheBallStores.Models.Voucher", b =>
                {
                    b.Property<string>("MaVoucher")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DonToiThieu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiGiamGia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuongConLai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("MaVoucher");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("TheBallStores.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("TheBallStores.Models.SanPhamChiTiet", "MaChiTietNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaChiTiet")
                        .HasConstraintName("FK__ChiTietDo__MaChi__4BAC3F29");

                    b.HasOne("TheBallStores.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK__ChiTietDo__MaDon__4AB81AF0");

                    b.Navigation("MaChiTietNavigation");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("TheBallStores.Models.DonHang", b =>
                {
                    b.HasOne("TheBallStores.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DonHangs__MaKH__47DBAE45");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("TheBallStores.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("TheBallStores.Models.SanPham", "MaSpNavigation")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HinhAnhSanPham_SanPham");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("TheBallStores.Models.SanPham", b =>
                {
                    b.HasOne("TheBallStores.Models.LoaiSanPham", "MaLoaiNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__SanPhams__MaLoai__3B75D760");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("TheBallStores.Models.SanPhamChiTiet", b =>
                {
                    b.HasOne("TheBallStores.Models.KichThuoc", "MaSizeNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSize")
                        .HasConstraintName("FK__SanPhamCh__MaSiz__403A8C7D");

                    b.HasOne("TheBallStores.Models.SanPham", "MaSpNavigation")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("MaSp")
                        .HasConstraintName("FK__SanPhamChi__MaSP__3F466844");

                    b.Navigation("MaSizeNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("TheBallStores.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("TheBallStores.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("TheBallStores.Models.KichThuoc", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("TheBallStores.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("TheBallStores.Models.SanPham", b =>
                {
                    b.Navigation("HinhAnhSanPhams");

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("TheBallStores.Models.SanPhamChiTiet", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
